CC=g++
CFLAGS=-Wall -std=c++20 -o3
BINS=redirectores 
all: clean redirectores 

lista1:
	$(CC) $(CFLAGS) -o redirectores redirectores.cpp

clean:
	@echo " [CLN] Removing binary files"
	@rm -f $(BINS)

